#!/usr/bin/env python
#
# Copyright 2009 Alfredo Deza
#
# Pacha Daemon

import os
import sys
import time
from optparse import OptionParser
from subprocess import call, Popen, PIPE
from lib import supay, log, hg
    
class Watcher(object):
     """Handles all the Reports to display"""
 
     def __init__(self,
                  vcs=None,
                  path=None):
         self.path = os.path.normpath(path)
         self.vcs = vcs
 
     def report(self):
         """Report if a file changed and the change has not been commited"""
         log.append(module='pachad', line='watching for changes in %s' % self.path)
         run = Runners(location=self.path)
         revision = run.hg_revision()[0]
         log.append(module='pachad', line='revision ID is: %s at %s' % (revision, self.path))
         while True:
            current_revision = run.hg_revision()[0]
            time.sleep(5)
            new_revision = run.hg_revision()[0]
            if current_revision != new_revision:
                log.append(module='pachad', line='found a new revision: %s at %s' % (new_revision, self.path))
                mercurial = hg.Hg(path=self.path)
                mercurial.push()
            if run.modified() is True:
                mercurial = hg.Hg(path=self.path)
                mercurial.commit()
                mercurial.push()

class Runners(object):
    """Handles everything related to Mercurial"""
 
    def __init__(self, location=None):
        self.location = location
        os.chdir(location) # change directory (HG bug)

    def hg_revision(self):
        """Gets the revision ID from the path"""
        changeset = run_command(std="stdout", cmd="hg head")[0]
        return changeset[-13:].split('\n')

    def modified(self):
        """Checks if a file has been modified and not commited"""
        out = run_command(std="stdout", cmd="hg st")
        dir = os.getcwd()
        for file in out:
            file_name = file[2:].split('\n')[0] # get a nice file name
            if file.startswith('M'):
                log.append(module='pachad', line='found modified file: %s' % file_name)
                return True
            else:
                return False
                log.append(module='pachad', line='no changes with: %s' % file_name)

def run_command(std, cmd):
    """Runs a command via Popen"""
    if std == "stderr":
        run = Popen(cmd, shell=True, stderr=PIPE)
        out = run.stderr.readlines()
    if std == "stdout":
        run = Popen(cmd, shell=True, stdout=PIPE, stderr=PIPE)
        out = run.stdout.readlines()
    return out


def main():
    """All command line options happen here"""
    parser = OptionParser()

    parser.add_option('--start', action="store_true",
           help="starts daemon")
    parser.add_option('--stop', action="store_true",
           help="stops daemons")
    
    options, arguments = parser.parse_args()

    # Cleanest way to show the help menu if no options are given
    if len(sys.argv) == 1:
        parser.print_help()

    if options.start:
        daemon = supay.Daemon(name='pachad', log=False)
        daemon.start()
        log.append(module='pachad', line='Daemon started')
        while True:
            watch = Watcher(path='/tmp/foo')
            watch.report()

    if options.stop:
        daemon = supay.Daemon(name='pachad', log=False)
        daemon.stop()
        log.append(module='pachad', line='Daemon stopped')

if __name__ == '__main__':
    main()

