#!/usr/bin/env python
#
# Copyright 2009-2010 Alfredo Deza
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Pacha Daemon

import os
import sys
import time
from optparse import OptionParser
from subprocess import Popen, PIPE
# fix for local imports
sys.path.append('/opt/pacha')
from lib import supay, log, hg, confparser, database
    
class Watcher(object):
    """Handles all the Reports to display"""
 
    def __init__(self,
                 path=None):
        self.path = os.path.normpath(path)
 
    def report(self):
        """Report if a file changed and the change has not been commited"""
        log.append(module='pachad', 
                line='watching for changes in %s' % self.path)
        run = Runners(location=self.path)
        revision = run.hg_revision()[0]
        log.append(module='pachad', 
                line='revision ID is: %s at %s' % (revision, self.path))
        current_revision = run.hg_revision()[0]
        new_revision = run.hg_revision()[0]
        if current_revision != new_revision:
            log.append(module='pachad', 
                    line='found a new revision: %s at %s' % (new_revision, 
                    self.path))
            mercurial = hg.Hg(path=self.path)
            mercurial.push()
        if run.modified() is True:
            mercurial = hg.Hg(path=self.path)
            mercurial.commit()
            mercurial.push()
            
class Runners(object):
    """Handles everything related to Mercurial calls"""
 
    def __init__(self, location=None):
        self.location = location
        os.chdir(location) # change directory (HG bug)

    def hg_revision(self):
        """Gets the revision ID from the path"""
        changeset = run_command(std="stdout", cmd="hg head")[0]
        return changeset[-13:].split('\n')

    def modified(self):
        """Checks if a file has been modified and not commited"""
        out = run_command(std="stdout", cmd="hg st")
        for line in out:
            file_name = line[2:].split('\n')[0] # get a nice file name
            if line.startswith('M'):
                log.append(module='pachad', 
                        line='found modified file: %s' % file_name)
                return True
            else:
                return False
                log.append(module='pachad', 
                        line='no changes with: %s' % file_name)

def run_command(std, cmd):
    """Runs a command via Popen"""
    if std == "stderr":
        run = Popen(cmd, shell=True, stderr=PIPE)
        out = run.stderr.readlines()
    if std == "stdout":
        run = Popen(cmd, shell=True, stdout=PIPE, stderr=PIPE)
        out = run.stdout.readlines()
    return out


def main():
    """All command line options happen here"""
    parser = OptionParser()

    parser.add_option('--start', action="store_true",
           help="starts daemon")
    parser.add_option('--stop', action="store_true",
           help="stops daemons")
    
    options, arguments = parser.parse_args()

    # Cleanest way to show the help menu if no options are given
    if len(sys.argv) == 1:
        parser.print_help()

    if options.start:
        daemon = supay.Daemon(name='pachad', log=False)
        daemon.start()
        log.append(module='pachad', line='Daemon started')
        db = database.Worker()
        while True:
            try:
                repos = db.get_repos()
                log.append(module='pachad', line='reading repos from database')
                pacha_conf = confparser.Parse(config='/opt/pacha/conf/pacha.conf')
                log.append(module='pachad', line='reading pacha.conf')
                pacha_conf.options()
                try:
                    master = pacha_conf.master
                    log.append(module='pachad.main', type='INFO',
                            line='machine set to master')
                    if master == 'True':
                        hg.update()
                except AttributeError, error:
                    log.append(module='pachad.main', type='INFO',
                            line='server not master: %s' % error)
                log.append(module='pachad.main', line='looping .repos')
                for repo in repos:
                    if os.path.exists(repo[1]): # catches a path no longer there...
                        watch = Watcher(path=repo[1])
                        watch.report()
                    else:
                        log.append(module='pachad', 
                         type='WARN', line='path %s does not exist' % repo[1])
                    break
                time.sleep(10)
            except Exception, error:
                log.append(module='pachad', type='ERROR', 
                        line='Fatal Exception - daemon killed')
                log.append(module='pachad', type='ERROR',
                        line='%s' % error)
                sys.exit(1)

    if options.stop:
        daemon = supay.Daemon(name='pachad', log=False)
        daemon.stop()
        log.append(module='pachad', line='Daemon stopped')

if __name__ == '__main__':
    main()

